gui:
  title: "&8&lMOB COINS"
  rows: 4
  decoration:
    mobcoins_item:
      material: "WATCH"
      name: "&b&lMOB COIN ITEMS"
      lore:
        - ""
        - "&2&l* &aTime Remaining&f: &7%normaltime%"
        - ""
        - "&7&o(( These items will automatically update to new items... ))"
      durability: 0
      slot: 5
    special_mobcoins_item:
      material: "WATCH"
      name: "&3&lSPECIAL MOB COIN ITEMS"
      lore:
        - ""
        - "&2&l* &aTime Remaining&f: &7%specialtime%"
        - ""
        - "&7&o(( These items will automatically update to new items... ))"
      durability: 0
      slot: 2
    amount_item:
      material: "DOUBLE_PLANT"
      name: "&3You currently have &b%coins% &3mobcoins"
      lore: []
      durability: 0
      slot: 27
    info_item:
      material: "BOOK"
      name: " "
      lore:
        - "&7&m-------------------------------------"
        - "&bMob Coins &7can be earned by killing &c&lHOSTILE &7mobs."
        - "&bMob Coins &7will allow you to buy items from the shop menu"
        - "&7Use &b/Mobcoins Help&7 for more!"
        - " "
        - "&3&lMobs that drop coins:"
        - "&bZombies, &bSkeletons and &bBlazes &7&o(5% chance)"
        - "&bCreepers and Endermans &7&o(8% chance)"
        - "&7&m-------------------------------------"
        - " "
      durability: 0
      slot: 35
  filler:
    enabled: true
    item:
      material: "STAINED_GLASS_PANE"
      name: " "
      durability: 15
gui_open:
  sound:
    enabled: true
    type: "ENDERDRAGON_HIT"
mobcoin_item:
  material: "DOUBLE_PLANT"
  name: "&b&lMob Coin &7(Rightclick to redeem)"
  lore:
    - "&3You can use these coins in &b/mobcoins"
    - "&3to purchase stuff"
mobcoin_normal_shop_update_hours: 24
mobcoin_special_shop_update_hours: 72
mobcoins_only_from_naturally_spawned_mods: false
received_mobcoin_from_mob_message_sent: true
close_gui_on_buy: true
stacking_support: true

NO_PERMISSION_MESSAGE: "&cYou do not have permission to execute this command"
USAGE_MESSAGE: "&cUsage: %usage%"
PLAYER_NOT_FOUND_MESSAGE: "&cCannot find the player %player%"
PROFILE_NOT_FOUND_MESSAGE: "&cCannot find the profile %profile%"
NOT_NUMERIC_MESSAGE: "&c%arg% should only contain numbers"
GAVE_MOBCOINS_MESSAGE: "&eYou gave &6%amount% &emobcoins to &6%player%"
RECEIVED_MOBCOINS_MESSAGE: "&eYou received &6%amount% &emobcoins from &6%sender%"
GAVE_MOBCOIN_ITEMS_MESSAGE: "&eYou gave &6%amount% &emobcoin items to &6%player%"
RECEIVED_MOBCOIN_ITEMS_MESSAGE: "&eYou received &6%amount% &emobcoin items from &6%sender%"
NOT_PLAYER_MESSAGE: "&cYou need to be a player to execute this command"
AMOUNT_CANT_BE_ZERO_MESSAGE: "&cThe withdrawal amount cannot be 0"
NOT_ENOUGH_MOBCOINS_MESSAGE: "&cYou do not have enough mobcoins to do that"
WITHDREW_MOBCOINS_MESSAGE: "&eYou withdrew &6%amount% &emobcoins"
BOUGHT_REWARD_MESSAGE: "&eYou bought %reward% &efor &6%amount% &emobcoins"
RECEIVED_MOBCOIN_FROM_MOB_MESSAGE: "&a&l+ %amount%⛁ Mobcoin &7(Mob)"
REDEEMED_MOBCOIN_MESSAGE: "&eYou redeemed &6%amount% &emobcoins"
MOBCOIN_NORMAL_SHOP_UPDATED_MESSAGE: "&e(&6&l!&e) The normal mobcoin items in &6/mobcoins &ehas been updated"
MOBCOIN_SPECIAL_SHOP_UPDATED_MESSAGE: "&e(&6&l!&e) The special mobcoin items in &6/mobcoins &ehas been updated"
MOBCOINS_OF_PLAYER_MESSAGE: "&6%player% &ehas &6%amount% &emobcoins"
PLAYER_NOT_ENOUGH_MOBCOINS: "&c%player% does not have %amount% mobcoins"
TOOK_MOBCOINS_MESSAGE: "&eYou took &6%amount% &emobcoins from &6%player%"
PLAYER_TOOK_MOBCOINS_MESSAGE: "&6%player% &etook &6%amount% &emobcoins from your balance"
SET_MOBCOINS_MESSAGE: "&6%player%&e's mobcoins balance has been set to &6%amount%"
YOUR_MOBCOINS_SET_MESSAGE: "&eYour mobcoins balance has been set to &6%amount% &eby &6%player%"
INVENTORY_FULL_MESSAGE: "&cYour inventory is full"
INVENTORY_GOT_FILLED_MESSAGE: "&eYour inventory got filled so you could only withdraw &6%amount% &emobcoins"
MOBCOINS_HELP_LORE:
  - '&8&m---------------------------'
  - '&3&l(!) Mobcoins Commands:'
  - '&b/mobcoins withdraw <amount>'
  - '&b/mobcoins viewcoins <player>'
  - '&8&m---------------------------'
MOBCOINS_HELP_ADMIN_LORE:
  - '&8&m---------------------------'
  - '&3&l(!) Mobcoins Commands:'
  - '&b/mobcoins withdraw <amount>'
  - '&b/mobcoins viewcoins <player>'
  - ''
  - '&3&l(!) Admin Commands:'
  - '&b/mobcoins give <player> <amount> [-s]'
  - '&b/mobcoins take <player> <amount>'
  - '&b/mobcoins set <player> <amount>'
  - '&b/mobcoins giveitem <player> <amount>'
  - '&b/mobcoins refresh <category>'
  - '&b/mobcoins reload'
  - '&8&m---------------------------'