main: me.swanis.mobcoins.MobCoins
name: SuperMobCoins
version: 2.1.2
author: Swanis
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, HolographicDisplays, WildStacker]

commands:
  mobcoins:
    aliases: [transfer]