main: me.swanis.mobcoins.MobCoins
name: SuperMobCoins
version: 2.3.1
author: Swanis
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, HolographicDisplays, WildStacker]
api-version: 1.13

commands:
  mobcoins:
    aliases: [transfer]