main: me.swanis.mobcoins.MobCoins
name: SuperMobCoins
version: 2.2.5
author: Swanis
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, HolographicDisplays, WildStacker]
api-version: 1.14

commands:
  mobcoins:
    aliases: [transfer]