package me.swanis.mobcoins;

import me.swanis.mobcoins.utils.Sounds;
import me.swanis.mobcoins.utils.StringUtil;
import org.bukkit.Material;
import org.bukkit.Sound;

import java.util.ArrayList;
import java.util.List;

public class Configuration {

    public static String GUI_TITLE;
    public static int GUI_ROWS;
    public static Material GUI_MOBCOINS_ITEM_MATERIAL;
    public static int GUI_MOBCOINS_ITEM_SLOT;
    public static String GUI_MOBCOINS_ITEM_NAME;
    public static List<String> GUI_MOBCOINS_ITEM_LORE = new ArrayList<>();
    public static short GUI_MOBCOINS_ITEM_DURABILITY;
    public static Material GUI_SPECIAL_MOBCOINS_ITEM_MATERIAL;
    public static int GUI_SPECIAL_MOBCOINS_ITEM_SLOT;
    public static String GUI_SPECIAL_MOBCOINS_ITEM_NAME;
    public static List<String> GUI_SPECIAL_MOBCOINS_ITEM_LORE = new ArrayList<>();
    public static short GUI_SPECIAL_MOBCOINS_ITEM_DURABILITY;
    public static Material GUI_INFO_ITEM_MATERIAL;
    public static int GUI_INFO_ITEM_SLOT;
    public static String GUI_INFO_ITEM_NAME;
    public static List<String> GUI_INFO_ITEM_LORE = new ArrayList<>();
    public static short GUI_INFO_ITEM_DURABILITY;
    public static Material GUI_AMOUNT_ITEM_MATERIAL;
    public static int GUI_AMOUNT_ITEM_SLOT;
    public static String GUI_AMOUNT_ITEM_NAME;
    public static List<String> GUI_AMOUNT_ITEM_LORE = new ArrayList<>();
    public static short GUI_AMOUNT_ITEM_DURABILITY;
    public static boolean GUI_FILLER_ENABLED;
    public static Material GUI_FILLER_ITEM_MATERIAL;
    public static String GUI_FILLER_ITEM_NAME;
    public static short GUI_FILLER_ITEM_DURABILITY;
    public static Material MOBCOIN_ITEM_MATERIAL;
    public static String MOBCOIN_ITEM_NAME;
    public static List<String> MOBCOIN_ITEM_LORE = new ArrayList<>();
    public static int MOBCOIN_NORMAL_SHOP_UPDATE_HOURS;
    public static int MOBCOIN_SPECIAL_SHOP_UPDATE_HOURS;
    public static boolean GUI_OPEN_SOUND_ENABLED;
    public static Sound GUI_OPEN_SOUND_TYPE;
    public static boolean MOBCOINS_ONLY_FROM_NATURALLY_SPAWNED_MOBS;
    public static boolean RECEIVED_MOBCOIN_FROM_MOB_MESSAGE_SENT;
    public static boolean CLOSE_GUI_ON_BUY;
    public static boolean STACKING_SUPPORT;

    public static String NO_PERMISSION_MESSAGE;
    public static String USAGE_MESSAGE;
    public static String PLAYER_NOT_FOUND_MESSAGE;
    public static String PROFILE_NOT_FOUND_MESSAGE;
    public static String NOT_NUMERIC_MESSAGE;
    public static String GAVE_MOBCOINS_MESSAGE;
    public static String RECEIVED_MOBCOINS_MESSAGE;
    public static String GAVE_MOBCOIN_ITEMS_MESSAGE;
    public static String RECEIVED_MOBCOIN_ITEMS_MESSAGE;
    public static String NOT_PLAYER_MESSAGE;
    public static String AMOUNT_CANT_BE_ZERO_MESSAGE;
    public static String NOT_ENOUGH_MOBCOINS_MESSAGE;
    public static String WITHDREW_MOBCOINS_MESSAGE;
    public static String BOUGHT_REWARD_MESSAGE;
    public static String RECEIVED_MOBCOIN_FROM_MOB_MESSAGE;
    public static String REDEEMED_MOBCOIN_MESSAGE;
    public static String MOBCOIN_NORMAL_SHOP_UPDATED_MESSAGE;
    public static String MOBCOIN_SPECIAL_SHOP_UPDATED_MESSAGE;
    public static String MOBCOINS_OF_PLAYER_MESSAGE;
    public static String PLAYER_NOT_ENOUGH_MOBCOINS;
    public static String TOOK_MOBCOINS_MESSAGE;
    public static String PLAYER_TOOK_MOBCOINS_MESSAGE;
    public static String SET_MOBCOINS_MESSAGE;
    public static String YOUR_MOBCOINS_SET_MESSAGE;
    public static String INVENTORY_FULL_MESSAGE;
    public static String INVENTORY_GOT_FILLED_MESSAGE;
    public static List<String> MOBCOINS_HELP_LORE = new ArrayList<>();
    public static List<String> MOBCOINS_HELP_ADMIN_LORE = new ArrayList<>();

    public Configuration(MobCoins instance) {
        GUI_TITLE = StringUtil.color(instance.getConfig().getString("gui.title"));
        GUI_ROWS =  instance.getConfig().getInt("gui.rows");
        GUI_MOBCOINS_ITEM_MATERIAL = Material.valueOf(instance.getConfig().getString("gui.mobcoins_item.material"));
        GUI_MOBCOINS_ITEM_SLOT = instance.getConfig().getInt("gui.mobcoins_item.slot");
        GUI_MOBCOINS_ITEM_NAME = StringUtil.color(instance.getConfig().getString("gui.mobcoins_item.name"));
        Configuration.GUI_MOBCOINS_ITEM_LORE.clear();
        instance.getConfig().getStringList("gui.mobcoins_item.lore").forEach(string -> Configuration.GUI_MOBCOINS_ITEM_LORE.add(StringUtil.color(string)));
        GUI_MOBCOINS_ITEM_DURABILITY = (short) instance.getConfig().getInt("gui.mobcoins_item.durability");
        GUI_SPECIAL_MOBCOINS_ITEM_MATERIAL = Material.valueOf(instance.getConfig().getString("gui.special_mobcoins_item.material"));
        GUI_SPECIAL_MOBCOINS_ITEM_SLOT = instance.getConfig().getInt("gui.special_mobcoins_item.slot");
        GUI_SPECIAL_MOBCOINS_ITEM_NAME = StringUtil.color(instance.getConfig().getString("gui.special_mobcoins_item.name"));
        Configuration.GUI_SPECIAL_MOBCOINS_ITEM_LORE.clear();
        instance.getConfig().getStringList("gui.special_mobcoins_item.lore").forEach(string -> Configuration.GUI_SPECIAL_MOBCOINS_ITEM_LORE.add(StringUtil.color(string)));
        GUI_SPECIAL_MOBCOINS_ITEM_DURABILITY = (short) instance.getConfig().getInt("gui.special_mobcoins_item.durability");
        GUI_INFO_ITEM_MATERIAL = Material.valueOf(instance.getConfig().getString("gui.info_item.material"));
        GUI_INFO_ITEM_SLOT = instance.getConfig().getInt("gui.info_item.slot");
        GUI_INFO_ITEM_NAME = StringUtil.color(instance.getConfig().getString("gui.info_item.name"));
        Configuration.GUI_INFO_ITEM_LORE.clear();
        instance.getConfig().getStringList("gui.info_item.lore").forEach(string -> Configuration.GUI_INFO_ITEM_LORE.add(StringUtil.color(string)));
        GUI_INFO_ITEM_DURABILITY = (short) instance.getConfig().getInt("gui.info_item.durability");
        GUI_AMOUNT_ITEM_MATERIAL = Material.valueOf(instance.getConfig().getString("gui.amount_item.material"));
        GUI_AMOUNT_ITEM_SLOT = instance.getConfig().getInt("gui.amount_item.slot");
        GUI_AMOUNT_ITEM_NAME = StringUtil.color(instance.getConfig().getString("gui.amount_item.name"));
        Configuration.GUI_AMOUNT_ITEM_LORE.clear();
        instance.getConfig().getStringList("gui.amount_item.lore").forEach(string -> Configuration.GUI_AMOUNT_ITEM_LORE.add(StringUtil.color(string)));
        GUI_AMOUNT_ITEM_DURABILITY = (short) instance.getConfig().getInt("gui.amount_item.durability");
        GUI_FILLER_ENABLED = instance.getConfig().getBoolean("gui.filler.enabled");
        GUI_FILLER_ITEM_MATERIAL = Material.valueOf(instance.getConfig().getString("gui.filler.item.material"));
        GUI_FILLER_ITEM_NAME = StringUtil.color(instance.getConfig().getString("gui.filler.item.name"));
        GUI_FILLER_ITEM_DURABILITY = (short) instance.getConfig().getInt("gui.filler.item.durability");
        GUI_OPEN_SOUND_ENABLED = instance.getConfig().getBoolean("gui_open.sound.enabled");
        GUI_OPEN_SOUND_TYPE = Sounds.valueOf(instance.getConfig().getString("gui_open.sound.type")).bukkitSound();
        MOBCOIN_ITEM_MATERIAL = Material.valueOf(instance.getConfig().getString("mobcoin_item.material"));
        MOBCOIN_ITEM_NAME = StringUtil.color(instance.getConfig().getString("mobcoin_item.name"));
        Configuration.MOBCOIN_ITEM_LORE.clear();
        instance.getConfig().getStringList("mobcoin_item.lore").forEach(string -> Configuration.MOBCOIN_ITEM_LORE.add(StringUtil.color(string)));
        MOBCOIN_NORMAL_SHOP_UPDATE_HOURS = instance.getConfig().getInt("mobcoin_normal_shop_update_hours");
        MOBCOIN_SPECIAL_SHOP_UPDATE_HOURS = instance.getConfig().getInt("mobcoin_special_shop_update_hours");
        MOBCOINS_ONLY_FROM_NATURALLY_SPAWNED_MOBS = instance.getConfig().getBoolean("mobcoins_only_from_naturally_spawned_mods");
        RECEIVED_MOBCOIN_FROM_MOB_MESSAGE_SENT = instance.getConfig().getBoolean("received_mobcoin_from_mob_message_sent");
        CLOSE_GUI_ON_BUY = instance.getConfig().getBoolean("close_gui_on_buy");
        STACKING_SUPPORT = instance.getConfig().getBoolean("stacking_support");

        NO_PERMISSION_MESSAGE = StringUtil.color(instance.getConfig().getString("NO_PERMISSION_MESSAGE"));
        USAGE_MESSAGE = StringUtil.color(instance.getConfig().getString("USAGE_MESSAGE"));
        PLAYER_NOT_FOUND_MESSAGE = StringUtil.color(instance.getConfig().getString("PLAYER_NOT_FOUND_MESSAGE"));
        PROFILE_NOT_FOUND_MESSAGE = StringUtil.color(instance.getConfig().getString("PROFILE_NOT_FOUND_MESSAGE"));
        NOT_NUMERIC_MESSAGE = StringUtil.color(instance.getConfig().getString("NOT_NUMERIC_MESSAGE"));
        GAVE_MOBCOINS_MESSAGE = StringUtil.color(instance.getConfig().getString("GAVE_MOBCOINS_MESSAGE"));
        RECEIVED_MOBCOINS_MESSAGE = StringUtil.color(instance.getConfig().getString("RECEIVED_MOBCOINS_MESSAGE"));
        GAVE_MOBCOIN_ITEMS_MESSAGE = StringUtil.color(instance.getConfig().getString("GAVE_MOBCOIN_ITEMS_MESSAGE"));
        RECEIVED_MOBCOIN_ITEMS_MESSAGE = StringUtil.color(instance.getConfig().getString("RECEIVED_MOBCOIN_ITEMS_MESSAGE"));
        NOT_PLAYER_MESSAGE = StringUtil.color(instance.getConfig().getString("NOT_PLAYER_MESSAGE"));
        AMOUNT_CANT_BE_ZERO_MESSAGE = StringUtil.color(instance.getConfig().getString("AMOUNT_CANT_BE_ZERO_MESSAGE"));
        NOT_ENOUGH_MOBCOINS_MESSAGE = StringUtil.color(instance.getConfig().getString("NOT_ENOUGH_MOBCOINS_MESSAGE"));
        WITHDREW_MOBCOINS_MESSAGE = StringUtil.color(instance.getConfig().getString("WITHDREW_MOBCOINS_MESSAGE"));
        BOUGHT_REWARD_MESSAGE = StringUtil.color(instance.getConfig().getString("BOUGHT_REWARD_MESSAGE"));
        RECEIVED_MOBCOIN_FROM_MOB_MESSAGE = StringUtil.color(instance.getConfig().getString("RECEIVED_MOBCOIN_FROM_MOB_MESSAGE"));
        REDEEMED_MOBCOIN_MESSAGE = StringUtil.color(instance.getConfig().getString("REDEEMED_MOBCOIN_MESSAGE"));
        MOBCOIN_NORMAL_SHOP_UPDATED_MESSAGE = StringUtil.color(instance.getConfig().getString("MOBCOIN_NORMAL_SHOP_UPDATED_MESSAGE"));
        MOBCOIN_SPECIAL_SHOP_UPDATED_MESSAGE = StringUtil.color(instance.getConfig().getString("MOBCOIN_SPECIAL_SHOP_UPDATED_MESSAGE"));
        MOBCOINS_OF_PLAYER_MESSAGE = StringUtil.color(instance.getConfig().getString("MOBCOINS_OF_PLAYER_MESSAGE"));
        PLAYER_NOT_ENOUGH_MOBCOINS = StringUtil.color(instance.getConfig().getString("PLAYER_NOT_ENOUGH_MOBCOINS"));
        TOOK_MOBCOINS_MESSAGE = StringUtil.color(instance.getConfig().getString("TOOK_MOBCOINS_MESSAGE"));
        PLAYER_TOOK_MOBCOINS_MESSAGE = StringUtil.color(instance.getConfig().getString("PLAYER_TOOK_MOBCOINS_MESSAGE"));
        SET_MOBCOINS_MESSAGE = StringUtil.color(instance.getConfig().getString("SET_MOBCOINS_MESSAGE"));
        YOUR_MOBCOINS_SET_MESSAGE = StringUtil.color(instance.getConfig().getString("YOUR_MOBCOINS_SET_MESSAGE"));
        INVENTORY_FULL_MESSAGE = StringUtil.color(instance.getConfig().getString("INVENTORY_FULL_MESSAGE"));
        INVENTORY_GOT_FILLED_MESSAGE = StringUtil.color(instance.getConfig().getString("INVENTORY_GOT_FILLED_MESSAGE"));
        MOBCOINS_HELP_LORE.clear();
        instance.getConfig().getStringList("MOBCOINS_HELP_LORE").forEach(string -> Configuration.MOBCOINS_HELP_LORE.add(StringUtil.color(string)));
        MOBCOINS_HELP_ADMIN_LORE.clear();
        instance.getConfig().getStringList("MOBCOINS_HELP_ADMIN_LORE").forEach(string -> Configuration.MOBCOINS_HELP_ADMIN_LORE.add(StringUtil.color(string)));
    }
}
